# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Compilar Documentação LaTeX

# Gatilhos: quando este workflow deve ser executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

# Tarefas a serem executadas
jobs:
  compile_latex:
    # Usa a versão mais recente do Ubuntu como ambiente
    runs-on: ubuntu-latest

    # Passos da tarefa
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX com latexmk
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: latex/
          compiler: latexmk
          args: -pdf -shell-escape -file-line-error

      - name: Renomear PDF
        run: mv latex/main.pdf Documentacao_UFSKernel.pdf

      # 4. Publica o PDF em uma Release "Latest"
      - name: Publicar PDF na Release
        # Garante que a release só seja atualizada quando o código for aceito na main
        if: github.event_name == 'push'
        # >>> ================================== <<<
        uses: softprops/action-gh-release@v2
        with:
          files: Documentacao_UFSKernel.pdf
          tag_name: Documentação-Atualizada
          prerelease: false
          make_latest: true
